### PR TITLE
DE42651: [Engagement] [Course Access Over Time] Non-selected course hides active one

### PR DESCRIPTION
**Pull request by Vitalii-Misechko**
[DE42651](https://rally1.rallydev.com/#/23525809118d/iterationstatus?Iteration=%2Fiteration%2F450581316144&Name=%5BEngagement%5D%20%5BCourse%20Access%20Over%20Time%5D%20Non-selected%20course%20hides%20active%20one&Priority=Low&Project=%2Fproject%2F23525809118&detail=%2Fdefect%2F502765078392&iteration=u&rankTo=BOTTOM&sharedViewId=328666453148&view=dc9e7043-1cf6-486d-a4aa-3a212976e789&fdp=true?fdp=true): [Engagement] [Course Access Over Time] Non-selected course hides active one

PR changes chart type for Course Access Overtime. It sets it to line type instead of area type. In addition, PR changes `zIndex` of active course in order to show it upfront ofother courses.

FYI @anhill-D2L @hyehayes @NicholasHallman @MykolaGalian 

* Functional Testing 
  * Selecting a course causes the selected course to appear in front of other
* Security, devops, perf: N/A
* UX and docs
  * [x] Demo
  
  
 ### Before
 
 
image

### After 

Bring-upfront-active-course-3

### CODE REVIEW

**Comment by johngwilkinson** [comment]
This looks like a good fix, but it just occurred to me: shouldn't these be stacked area charts? Can you check with Kevin whether the areas should be overlapping like this at all? It means that some courses could be hidden behind others when none are selected, and looks odd to me.

**Comment by Vitalii-Misechko** [comment]
> This looks like a good fix, but it just occurred to me: shouldn't these be stacked area charts? Can you check with Kevin whether the areas should be overlapping like this at all? It means that some courses could be hidden behind others when none are selected, and looks odd to me.

It doesn't look good in comparison with demo data. But, it is what stacked area chart shows for data generated by LMS. It might be that another type of chart would represent these data better. It is definitely worth checking with Kevin.

**Comment by Vitalii-Misechko** [comment]
Updated the base of the PR in order to show these changes more clear

**Comment by johngwilkinson** [comment]
I don't see the settings for stacked area in our code, but I might be missing them.
```
chart: {
 type: 'area'`
```
and
```
plotOptions: {
        area: {
            stacking: 'normal'
```

like this: https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/area-stacked

**Comment by johngwilkinson** [comment]
Looks good. Just to check: do the interactions still work?

**Comment by Vitalii-Misechko** [comment]
> Looks good. Just to check: do the interactions still work?

Yes, they work. When I click on a line(previously area) it applies a filter.

P.S. Going to post here complex charts from the defect to see how the solution works with them when Draco lms becomes available for updates

**Review by johngwilkinson — APPROVED** [review]

**Comment by Vitalii-Misechko** [comment]
- [ ] Waiting on an alternative approach rejection [here ](https://d2l.slack.com/archives/CMNGJ22G0/p1614685886079200?thread_ts=1614290601.054200&cid=CMNGJ22G0)

**Review by NicholasHallman — APPROVED** [review]

**Comment by Vitalii-Misechko** [comment]
> * [x]  Waiting on an alternative approach rejection [here ](https://d2l.slack.com/archives/CMNGJ22G0/p1614685886079200?thread_ts=1614290601.054200&cid=CMNGJ22G0)

It seems that the initial solution that employs an area chart is the least confusing by now. Reverted  "Use line chart instead of area chart" - commit

**Review by johngwilkinson — APPROVED** [review]
Not sure if other changes will be needed client-side, but I'm guessing this should cover it.

**Pull request merged**
