### PR TITLE
Update discussion activity title padding

### PR DESCRIPTION
**Pull request by JikaiLong**
Update the padding for Discussion Activity Card to match the new padding requirement for cards. 
Design is responsive for both small and big card sizes 

Updated view:
image

Skeleton View:
image
@Brightspace/draco-vis

### CODE REVIEW

**Comment by Vitalii-Misechko** [comment]
It's odd that sauce tests are failing. 
Anyway `Discussion Activity` chart has a different height than other cards. I think we should fix it

**Comment by NicholasHallman** [comment]
Handy trick, Firefox has guide lines when you inspect something with dev tools in case you aren't sure if something is the right size or lined up 

Screenshot (8)

**Comment by JikaiLong** [comment]
Updated: Discussion Activity Height now match with other cards. 
image

**Review by Vitalii-Misechko — APPROVED** [review]
LGTM!

**Review by NicholasHallman — APPROVED** [review]
👍

**Pull request merged**
