### PR TITLE
Fix: Explicit tree filter appearing in url state

### PR DESCRIPTION
**Pull request by NicholasHallman**
This is a revert of my changes

### CODE REVIEW

**Comment by NicholasHallman** [comment]
@bemailloux this fixes the problem you are having with reloads

**Review by bemailloux — COMMENTED** [review]
Oops my bad 😅

**Review by bemailloux — APPROVED** [review]

**Comment by NicholasHallman** [comment]
> Oops my bad 😅

Nope it's on me I should have tested it lmao

**Review by johngwilkinson — APPROVED** [review]
Aha! I saw that, then it went away, so I thought maybe it was just a weird demo page thing. Thanks for the fix.

**Pull request merged**
