### PR TITLE
Labels Translation Pr's

### PR DESCRIPTION
**Pull request by NicholasHallman**
This will label a PR as `translation` if the pr makes changes to files in the locales folder. 

We can use this to filter issues with the github slack bot and have it notify us if there are translations updates in draco-vis 

This is to satisfy our conversation around translations pr notification in retro

### CODE REVIEW

**Comment by NicholasHallman** [comment]
Does adding a comment post to slack?

**Comment by bemailloux** [comment]
Does this work now? Not sure whether to approve or not

**Comment by NicholasHallman** [comment]
> Does this work now? Not sure whether to approve or not

Yep this works you should see a `translation` tag in this PR.

> Does adding a comment post to slack?
nope

Here I was checking that to make sure that if we talked in the pr it wouldn't spam the channel. So it's good that the bot didn't say anything

**Comment by bemailloux** [comment]
When does the "posting to slack" part come in?

**Comment by NicholasHallman** [comment]
> When does the "posting to slack" part come in?

I've set up a test bot in #test-translation-filter-github so you can hop in there. I can't really test untill this is merged but you can see there how I've configured the bot

**Review by bemailloux — APPROVED** [review]

**Review by anhill-D2L — APPROVED** [review]

**Pull request merged**
